### ISSUE TITLE
autonomousRotateIntCommand

### ISSUE THREAD

**Issue by Team2890** [Team2890/Icarus#1]
autonomousRotateIntCommand is a command class, which should cause the robot to rotate a set degree value upon execution.

**Comment by Team2890** [comment]
Current implementation (as of 2/10/18) sets a speed rather than taking Gyro input to determine when to stop rotating.

**Comment by Team2890** [comment]
Gyro needs to be implemented in Java code

**Comment by StudyFaith24** [comment]
I've fixed this and will post solution later

**Comment by Podcakero** [comment]
added Math.abs() for the rotate right if structure so that negative gyro angle targets will function correctly.
