### ISSUE TITLE
Drive forward until distance using rangefinder

### ISSUE THREAD

**Issue by TMacTheFirst** [Team2890/Icarus#17]
Somebody needs to tell the build team we need one on the robot

**Comment by SamSunvold** [comment]
Didnt get done today. Will finish tomorrow

**Comment by TMacTheFirst** [comment]
Orlando wrote the code and it looked good. Still needs to be tested on the real robot

**Comment by SamSunvold** [comment]
Range Finder tested and working. Added to command and is working.
